services:
  app:
    build: .
    container_name: notes
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgres://postgres:root@postgres:5432/notesdb
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npx sequelize-cli db:migrate && npm run dev"
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - notes_network

  postgres:
    image: postgres:14
    container_name: notes_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notes_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - notes_network

volumes:
  postgres_data:

networks:
  notes_network:
    driver: bridge